# Generated by Django 6.0.5 on 2026-05-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmeetsApp', '0002_event_featured_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
