# Generated by Django 6.0.5 on 2026-05-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmeetsApp', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Meet-up', 'Meet-up')], default='Meet-up', max_length=20),
        ),
    ]
